### ISSUE TITLE
Plans to use "GOOGLE_APPLICATION_CREDENTIALS_JSON" (FEEDS)

### ISSUE THREAD

**Issue by 1eliton** [scrapy/scrapy#5769]
Hello,

I am currently calling the crawlers from Airflow, using `PythonOperator`. It works perfect. But, because of that, I cannot set a env variable named `GOOGLE_APPLICATION_CREDENTIALS` with a path to the json file, once its a limitation I have (fully managed environment, can't edit the image). Instead of it, I have the content of the json, provided by an Airflow Connection.

I know that besides `GOOGLE_APPLICATION_CREDENTIALS` env var google credentials mechanism ([google-cloud-storage](https://cloud.google.com/storage/docs/reference/libraries#client-libraries-install-python) lib) also "looks" to `GOOGLE_APPLICATION_CREDENTIALS_JSON` which exactly what I do have when I call a `crawl(MySpider)`. 

What I also tried in order to use the content of json credentials instead of this env var was this [scrapy-s3pipeline](https://github.com/orangain/scrapy-s3pipeline) but somehow it is not working (the feed is not exported).

So, my question is more about if you plan to move into this direction, providing this different manner to handle an authentication in order to allow a crawler to FEED to GCS.

Thank you in advance.

**Comment by Gallaecio** [comment]
Authentication is not implemented in Scrapy, it is part of the library we use, which is the official one, [as the documentation indicates](https://docs.scrapy.org/en/latest/topics/feed-exports.html#topics-feed-storage-gcs).

I don‘t think it makes sense to make Scrapy handle what you are suggesting, if anything the upstream library should be doing that.

**Comment by 1eliton** [comment]
Understood. What I meant by that is perhaps it could be possible to offer a additional layer with this `GOOGLE_APPLICATION_CREDENTIALS_JSON` parameter to use as an authentication method, then its possible to use something like:

```
from google.oauth2 import service_account
credentials = service_account.Credentials.from_service_account_info(
    json.loads(json_content_var)
)
```

Because currently is not possible to feed to gcs, regarding this Google Cloud Composer environment that does not allow us the possibility to persist a file in order to use its content to authenticate. 

So, in my case I can't proceed calling a crawler from Composer. Please, correct me if I am wrong.

Again, I thank you

**Comment by Gallaecio** [comment]
I really think the place to discuss this is e.g. https://github.com/googleapis/google-auth-library-python/issues/328, not the Scrapy repository, unless there is a good reason to address this issue in Scrapy specifically.

**Comment by Gallaecio** [comment]
> I know that besides `GOOGLE_APPLICATION_CREDENTIALS` env var google credentials mechanism ([google-cloud-storage](https://cloud.google.com/storage/docs/reference/libraries#client-libraries-install-python) lib) also "looks" to `GOOGLE_APPLICATION_CREDENTIALS_JSON` which exactly what I do have when I call a `crawl(MySpider)`.

Unless I am missing something, it sounds like things should be working for you.

**Comment by 1eliton** [comment]
> > I know that besides `GOOGLE_APPLICATION_CREDENTIALS` env var google credentials mechanism ([google-cloud-storage](https://cloud.google.com/storage/docs/reference/libraries#client-libraries-install-python) lib) also "looks" to `GOOGLE_APPLICATION_CREDENTIALS_JSON` which exactly what I do have when I call a `crawl(MySpider)`.
> 
> Unless I am missing something, it sounds like things should be working for you.

I was wrong when I mentioned this reference. Some libs use this approach (like [this](https://pypi.org/project/scrapy-s3pipeline/)) but officially it is not implemented.
I could just now solve my issue persisting the json file in a bucket that is visible from Composer, according to [official docs recommendation](https://cloud.google.com/composer/docs/composer-2/cloud-storage#data).

I appreciate your time.
